# Generated by Django 6.0.3 on 2026-04-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон для связи'),
        ),
    ]
